### ISSUE TITLE
Unable to playback

### ISSUE THREAD

**Issue by kabhay** [Samsung/HbbPlayer#1]
Hi, 

I downloaded the entire zip and launched the index.cehtml in latest (40.0) opera browser. I could not see anything. However when I looked into the developer tools, I could see oipfObjectFactory is not defined line 91. 

My URL is as follows:

file:///e:/HbbPlayer-master/HbbPlayer-master/index.cehtml?url=file:///e:/HbbPlayer-master/HbbPlayer-master/sample.mp4&type=PLAYER_TYPE

Please let me know how to launch and see the video playback. 

Warm Regards,
-Abhay.

**Comment by KLUSEK** [comment]
Hi,

the oipfObjectFactory is not defined because you are trying to launch this application on WebBrowser, when this is designed to run on TV terminals with HbbTV support.

If you really want to run it in WebBrowser try to use FireHbbTV extension for Firefox which has limited emulation for required objects like oipfObjectFactory.

**Comment by steven-ellis** [comment]
We've got some live HbbTV compatible streams here in NZ that I'd also like to test out using FireHbbTV plus the Samsung player.

Here are some sample URLS
- http://mwhbbtv.fvpnz.co.nz/main.html - Loads but videos won't play
- http://mtshbbtv.fvpnz.co.nz/  - doesn't load
- http://static.tvnz.co.nz/apps/hbbtv/latest-prod/main.html - Requires registration

I'd be very interested to see how we can us FireHbbTV in conjunction with the Samsung player.

**Comment by steven-ellis** [comment]
Example test URL 
- http://localhost/hbbtv/index.cehtml?url=http://mwhbbtv.fvpnz.co.nz/main.html&type=html5

I've got the Samsung hbbtv code hosted locally being served up by Apache, plus my firefox has the FireHbbTV plugin enabled.

Webdeveloper extensions shows the error
- ReferenceError: oipfObjectFactory is not defined

**Comment by KLUSEK** [comment]
Hi Steven,

I think you've got purpose of this code wrong. HbbTV Player is not supposed to "play" an HbbTV apps.
It is just an HbbTV app itself, implementing methods available in HbbTV Spec related to video playout.

That means you cannot use it to run HbbTV apps you listed above, but you can pass URL to video as parameter.

This code is designed to being run on compatible TV devices. FireHbbTV is only emulation and might not work as you see.

BR.

**Comment by steven-ellis** [comment]
Thanks for the heads up. So an option would be to look at integration so that FireHbbTV could call into HbbTVPlayer for the video playback portion?

**Comment by MHEG5** [comment]
Hi Steven,

HbbPlayer is one of the HbbTV applications which can run on FireHbbTV like the applications below.
http://mwhbbtv.fvpnz.co.nz/main.html
http://mtshbbtv.fvpnz.co.nz/
http://static.tvnz.co.nz/apps/hbbtv/latest-prod/main.html

Therefore, I don't believe that it will solve your problem.

As there is no perfect HbbTV emulator or simulator available in PC, it seems to me that you need to invest some money and effort to run the applications on real TV.

BR,

**Comment by mbudek** [comment]
Dear all,

from now on you can test HbbPlayer also in WebBrowser environment.

BR

**Comment by steven-ellis** [comment]
Can you provide an example of how you'd test this code in a Web Browser environment?

**Comment by mbudek** [comment]
As you have Apache server and Firefox with Fire TV plugin all you need to do is type path to index.cehtml file on your machine with address to mp4 file (it can be hosted local or remotely) and you can type PLAYER_TYPE e.g. html5

http://UTL_TO_HBBPLAYER/index.cehtml?url=URL_TO_VIDEO_FILE.mp4&type=PLAYER_TYPE

in my case i use path
http://localhost/HbbPlayer/index.cehtml?url=http://localhost/HbbPlayer/sample.mp4&type=html5

As URL_TO_VIDEO_FILE you can also use e.g. http://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_1mb.mp4 but it might take a while for downloading
